# Generated by Django 5.1.2 on 2025-03-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('verificador', 'Verificador')], default='verificador', max_length=20),
        ),
    ]
