# Generated by Django 5.1.2 on 2025-05-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_profesor_carrera'),
        ('horarios', '0002_assign_default_career'),
    ]

    operations = [
    ]
